const githubResult = '''
{
  "total_count": 3693,
  "incomplete_results": false,
  "items": [
    {
      "login": "cristiano",
      "id": 91686,
      "node_id": "MDQ6VXNlcjkxNjg2",
      "avatar_url": "https://avatars.githubusercontent.com/u/91686?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristiano",
      "html_url": "https://github.com/cristiano",
      "followers_url": "https://api.github.com/users/cristiano/followers",
      "following_url": "https://api.github.com/users/cristiano/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristiano/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristiano/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristiano/subscriptions",
      "organizations_url": "https://api.github.com/users/cristiano/orgs",
      "repos_url": "https://api.github.com/users/cristiano/repos",
      "events_url": "https://api.github.com/users/cristiano/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristiano/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianoliveira",
      "id": 3959744,
      "node_id": "MDQ6VXNlcjM5NTk3NDQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3959744?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianoliveira",
      "html_url": "https://github.com/cristianoliveira",
      "followers_url": "https://api.github.com/users/cristianoliveira/followers",
      "following_url": "https://api.github.com/users/cristianoliveira/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianoliveira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianoliveira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianoliveira/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianoliveira/orgs",
      "repos_url": "https://api.github.com/users/cristianoliveira/repos",
      "events_url": "https://api.github.com/users/cristianoliveira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianoliveira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianomatos",
      "id": 2413283,
      "node_id": "MDQ6VXNlcjI0MTMyODM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2413283?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianomatos",
      "html_url": "https://github.com/cristianomatos",
      "followers_url": "https://api.github.com/users/cristianomatos/followers",
      "following_url": "https://api.github.com/users/cristianomatos/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianomatos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianomatos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianomatos/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianomatos/orgs",
      "repos_url": "https://api.github.com/users/cristianomatos/repos",
      "events_url": "https://api.github.com/users/cristianomatos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianomatos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianoc",
      "id": 7965335,
      "node_id": "MDQ6VXNlcjc5NjUzMzU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7965335?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianoc",
      "html_url": "https://github.com/cristianoc",
      "followers_url": "https://api.github.com/users/cristianoc/followers",
      "following_url": "https://api.github.com/users/cristianoc/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianoc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianoc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianoc/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianoc/orgs",
      "repos_url": "https://api.github.com/users/cristianoc/repos",
      "events_url": "https://api.github.com/users/cristianoc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianoc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "CristianoRC",
      "id": 14987889,
      "node_id": "MDQ6VXNlcjE0OTg3ODg5",
      "avatar_url": "https://avatars.githubusercontent.com/u/14987889?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CristianoRC",
      "html_url": "https://github.com/CristianoRC",
      "followers_url": "https://api.github.com/users/CristianoRC/followers",
      "following_url": "https://api.github.com/users/CristianoRC/following{/other_user}",
      "gists_url": "https://api.github.com/users/CristianoRC/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CristianoRC/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CristianoRC/subscriptions",
      "organizations_url": "https://api.github.com/users/CristianoRC/orgs",
      "repos_url": "https://api.github.com/users/CristianoRC/repos",
      "events_url": "https://api.github.com/users/CristianoRC/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CristianoRC/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "CristianoFIlho",
      "id": 54041918,
      "node_id": "MDQ6VXNlcjU0MDQxOTE4",
      "avatar_url": "https://avatars.githubusercontent.com/u/54041918?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CristianoFIlho",
      "html_url": "https://github.com/CristianoFIlho",
      "followers_url": "https://api.github.com/users/CristianoFIlho/followers",
      "following_url": "https://api.github.com/users/CristianoFIlho/following{/other_user}",
      "gists_url": "https://api.github.com/users/CristianoFIlho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CristianoFIlho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CristianoFIlho/subscriptions",
      "organizations_url": "https://api.github.com/users/CristianoFIlho/orgs",
      "repos_url": "https://api.github.com/users/CristianoFIlho/repos",
      "events_url": "https://api.github.com/users/CristianoFIlho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CristianoFIlho/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristiano-belloni",
      "id": 315834,
      "node_id": "MDQ6VXNlcjMxNTgzNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/315834?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristiano-belloni",
      "html_url": "https://github.com/cristiano-belloni",
      "followers_url": "https://api.github.com/users/cristiano-belloni/followers",
      "following_url": "https://api.github.com/users/cristiano-belloni/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristiano-belloni/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristiano-belloni/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristiano-belloni/subscriptions",
      "organizations_url": "https://api.github.com/users/cristiano-belloni/orgs",
      "repos_url": "https://api.github.com/users/cristiano-belloni/repos",
      "events_url": "https://api.github.com/users/cristiano-belloni/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristiano-belloni/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianossd",
      "id": 4166006,
      "node_id": "MDQ6VXNlcjQxNjYwMDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4166006?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianossd",
      "html_url": "https://github.com/cristianossd",
      "followers_url": "https://api.github.com/users/cristianossd/followers",
      "following_url": "https://api.github.com/users/cristianossd/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianossd/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianossd/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianossd/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianossd/orgs",
      "repos_url": "https://api.github.com/users/cristianossd/repos",
      "events_url": "https://api.github.com/users/cristianossd/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianossd/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cbetta",
      "id": 7718,
      "node_id": "MDQ6VXNlcjc3MTg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7718?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cbetta",
      "html_url": "https://github.com/cbetta",
      "followers_url": "https://api.github.com/users/cbetta/followers",
      "following_url": "https://api.github.com/users/cbetta/following{/other_user}",
      "gists_url": "https://api.github.com/users/cbetta/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cbetta/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cbetta/subscriptions",
      "organizations_url": "https://api.github.com/users/cbetta/orgs",
      "repos_url": "https://api.github.com/users/cbetta/repos",
      "events_url": "https://api.github.com/users/cbetta/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cbetta/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "CristianoPro",
      "id": 32495828,
      "node_id": "MDQ6VXNlcjMyNDk1ODI4",
      "avatar_url": "https://avatars.githubusercontent.com/u/32495828?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CristianoPro",
      "html_url": "https://github.com/CristianoPro",
      "followers_url": "https://api.github.com/users/CristianoPro/followers",
      "following_url": "https://api.github.com/users/CristianoPro/following{/other_user}",
      "gists_url": "https://api.github.com/users/CristianoPro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CristianoPro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CristianoPro/subscriptions",
      "organizations_url": "https://api.github.com/users/CristianoPro/orgs",
      "repos_url": "https://api.github.com/users/CristianoPro/repos",
      "events_url": "https://api.github.com/users/CristianoPro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CristianoPro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "CristianoSantan",
      "id": 65695476,
      "node_id": "MDQ6VXNlcjY1Njk1NDc2",
      "avatar_url": "https://avatars.githubusercontent.com/u/65695476?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CristianoSantan",
      "html_url": "https://github.com/CristianoSantan",
      "followers_url": "https://api.github.com/users/CristianoSantan/followers",
      "following_url": "https://api.github.com/users/CristianoSantan/following{/other_user}",
      "gists_url": "https://api.github.com/users/CristianoSantan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CristianoSantan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CristianoSantan/subscriptions",
      "organizations_url": "https://api.github.com/users/CristianoSantan/orgs",
      "repos_url": "https://api.github.com/users/CristianoSantan/repos",
      "events_url": "https://api.github.com/users/CristianoSantan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CristianoSantan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "crisgon",
      "id": 11144937,
      "node_id": "MDQ6VXNlcjExMTQ0OTM3",
      "avatar_url": "https://avatars.githubusercontent.com/u/11144937?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/crisgon",
      "html_url": "https://github.com/crisgon",
      "followers_url": "https://api.github.com/users/crisgon/followers",
      "following_url": "https://api.github.com/users/crisgon/following{/other_user}",
      "gists_url": "https://api.github.com/users/crisgon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/crisgon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/crisgon/subscriptions",
      "organizations_url": "https://api.github.com/users/crisgon/orgs",
      "repos_url": "https://api.github.com/users/crisgon/repos",
      "events_url": "https://api.github.com/users/crisgon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/crisgon/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "crino",
      "id": 224396,
      "node_id": "MDQ6VXNlcjIyNDM5Ng==",
      "avatar_url": "https://avatars.githubusercontent.com/u/224396?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/crino",
      "html_url": "https://github.com/crino",
      "followers_url": "https://api.github.com/users/crino/followers",
      "following_url": "https://api.github.com/users/crino/following{/other_user}",
      "gists_url": "https://api.github.com/users/crino/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/crino/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/crino/subscriptions",
      "organizations_url": "https://api.github.com/users/crino/orgs",
      "repos_url": "https://api.github.com/users/crino/repos",
      "events_url": "https://api.github.com/users/crino/events{/privacy}",
      "received_events_url": "https://api.github.com/users/crino/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "csalmeida",
      "id": 12223613,
      "node_id": "MDQ6VXNlcjEyMjIzNjEz",
      "avatar_url": "https://avatars.githubusercontent.com/u/12223613?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/csalmeida",
      "html_url": "https://github.com/csalmeida",
      "followers_url": "https://api.github.com/users/csalmeida/followers",
      "following_url": "https://api.github.com/users/csalmeida/following{/other_user}",
      "gists_url": "https://api.github.com/users/csalmeida/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/csalmeida/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/csalmeida/subscriptions",
      "organizations_url": "https://api.github.com/users/csalmeida/orgs",
      "repos_url": "https://api.github.com/users/csalmeida/repos",
      "events_url": "https://api.github.com/users/csalmeida/events{/privacy}",
      "received_events_url": "https://api.github.com/users/csalmeida/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "CristianoDaSilvaFerreira",
      "id": 68359459,
      "node_id": "MDQ6VXNlcjY4MzU5NDU5",
      "avatar_url": "https://avatars.githubusercontent.com/u/68359459?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CristianoDaSilvaFerreira",
      "html_url": "https://github.com/CristianoDaSilvaFerreira",
      "followers_url": "https://api.github.com/users/CristianoDaSilvaFerreira/followers",
      "following_url": "https://api.github.com/users/CristianoDaSilvaFerreira/following{/other_user}",
      "gists_url": "https://api.github.com/users/CristianoDaSilvaFerreira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CristianoDaSilvaFerreira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CristianoDaSilvaFerreira/subscriptions",
      "organizations_url": "https://api.github.com/users/CristianoDaSilvaFerreira/orgs",
      "repos_url": "https://api.github.com/users/CristianoDaSilvaFerreira/repos",
      "events_url": "https://api.github.com/users/CristianoDaSilvaFerreira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CristianoDaSilvaFerreira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "CristianoNunes",
      "id": 4103715,
      "node_id": "MDQ6VXNlcjQxMDM3MTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4103715?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CristianoNunes",
      "html_url": "https://github.com/CristianoNunes",
      "followers_url": "https://api.github.com/users/CristianoNunes/followers",
      "following_url": "https://api.github.com/users/CristianoNunes/following{/other_user}",
      "gists_url": "https://api.github.com/users/CristianoNunes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CristianoNunes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CristianoNunes/subscriptions",
      "organizations_url": "https://api.github.com/users/CristianoNunes/orgs",
      "repos_url": "https://api.github.com/users/CristianoNunes/repos",
      "events_url": "https://api.github.com/users/CristianoNunes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CristianoNunes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "chsguitar1",
      "id": 5813336,
      "node_id": "MDQ6VXNlcjU4MTMzMzY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5813336?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chsguitar1",
      "html_url": "https://github.com/chsguitar1",
      "followers_url": "https://api.github.com/users/chsguitar1/followers",
      "following_url": "https://api.github.com/users/chsguitar1/following{/other_user}",
      "gists_url": "https://api.github.com/users/chsguitar1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chsguitar1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chsguitar1/subscriptions",
      "organizations_url": "https://api.github.com/users/chsguitar1/orgs",
      "repos_url": "https://api.github.com/users/chsguitar1/repos",
      "events_url": "https://api.github.com/users/chsguitar1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chsguitar1/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianonicolai",
      "id": 570894,
      "node_id": "MDQ6VXNlcjU3MDg5NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/570894?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianonicolai",
      "html_url": "https://github.com/cristianonicolai",
      "followers_url": "https://api.github.com/users/cristianonicolai/followers",
      "following_url": "https://api.github.com/users/cristianonicolai/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianonicolai/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianonicolai/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianonicolai/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianonicolai/orgs",
      "repos_url": "https://api.github.com/users/cristianonicolai/repos",
      "events_url": "https://api.github.com/users/cristianonicolai/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianonicolai/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianounix",
      "id": 694280,
      "node_id": "MDQ6VXNlcjY5NDI4MA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/694280?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianounix",
      "html_url": "https://github.com/cristianounix",
      "followers_url": "https://api.github.com/users/cristianounix/followers",
      "following_url": "https://api.github.com/users/cristianounix/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianounix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianounix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianounix/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianounix/orgs",
      "repos_url": "https://api.github.com/users/cristianounix/repos",
      "events_url": "https://api.github.com/users/cristianounix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianounix/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianogregnanin",
      "id": 3127475,
      "node_id": "MDQ6VXNlcjMxMjc0NzU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3127475?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianogregnanin",
      "html_url": "https://github.com/cristianogregnanin",
      "followers_url": "https://api.github.com/users/cristianogregnanin/followers",
      "following_url": "https://api.github.com/users/cristianogregnanin/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianogregnanin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianogregnanin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianogregnanin/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianogregnanin/orgs",
      "repos_url": "https://api.github.com/users/cristianogregnanin/repos",
      "events_url": "https://api.github.com/users/cristianogregnanin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianogregnanin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristiano-pacheco",
      "id": 5084933,
      "node_id": "MDQ6VXNlcjUwODQ5MzM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5084933?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristiano-pacheco",
      "html_url": "https://github.com/cristiano-pacheco",
      "followers_url": "https://api.github.com/users/cristiano-pacheco/followers",
      "following_url": "https://api.github.com/users/cristiano-pacheco/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristiano-pacheco/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristiano-pacheco/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristiano-pacheco/subscriptions",
      "organizations_url": "https://api.github.com/users/cristiano-pacheco/orgs",
      "repos_url": "https://api.github.com/users/cristiano-pacheco/repos",
      "events_url": "https://api.github.com/users/cristiano-pacheco/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristiano-pacheco/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianocasm",
      "id": 5498526,
      "node_id": "MDQ6VXNlcjU0OTg1MjY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5498526?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianocasm",
      "html_url": "https://github.com/cristianocasm",
      "followers_url": "https://api.github.com/users/cristianocasm/followers",
      "following_url": "https://api.github.com/users/cristianocasm/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianocasm/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianocasm/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianocasm/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianocasm/orgs",
      "repos_url": "https://api.github.com/users/cristianocasm/repos",
      "events_url": "https://api.github.com/users/cristianocasm/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianocasm/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Cristianojr9",
      "id": 42578466,
      "node_id": "MDQ6VXNlcjQyNTc4NDY2",
      "avatar_url": "https://avatars.githubusercontent.com/u/42578466?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Cristianojr9",
      "html_url": "https://github.com/Cristianojr9",
      "followers_url": "https://api.github.com/users/Cristianojr9/followers",
      "following_url": "https://api.github.com/users/Cristianojr9/following{/other_user}",
      "gists_url": "https://api.github.com/users/Cristianojr9/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Cristianojr9/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Cristianojr9/subscriptions",
      "organizations_url": "https://api.github.com/users/Cristianojr9/orgs",
      "repos_url": "https://api.github.com/users/Cristianojr9/repos",
      "events_url": "https://api.github.com/users/Cristianojr9/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Cristianojr9/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cfgnunes",
      "id": 5264823,
      "node_id": "MDQ6VXNlcjUyNjQ4MjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5264823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cfgnunes",
      "html_url": "https://github.com/cfgnunes",
      "followers_url": "https://api.github.com/users/cfgnunes/followers",
      "following_url": "https://api.github.com/users/cfgnunes/following{/other_user}",
      "gists_url": "https://api.github.com/users/cfgnunes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cfgnunes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cfgnunes/subscriptions",
      "organizations_url": "https://api.github.com/users/cfgnunes/orgs",
      "repos_url": "https://api.github.com/users/cfgnunes/repos",
      "events_url": "https://api.github.com/users/cfgnunes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cfgnunes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianovagos",
      "id": 9096986,
      "node_id": "MDQ6VXNlcjkwOTY5ODY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9096986?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianovagos",
      "html_url": "https://github.com/cristianovagos",
      "followers_url": "https://api.github.com/users/cristianovagos/followers",
      "following_url": "https://api.github.com/users/cristianovagos/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianovagos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianovagos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianovagos/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianovagos/orgs",
      "repos_url": "https://api.github.com/users/cristianovagos/repos",
      "events_url": "https://api.github.com/users/cristianovagos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianovagos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianomg",
      "id": 53766118,
      "node_id": "MDQ6VXNlcjUzNzY2MTE4",
      "avatar_url": "https://avatars.githubusercontent.com/u/53766118?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianomg",
      "html_url": "https://github.com/cristianomg",
      "followers_url": "https://api.github.com/users/cristianomg/followers",
      "following_url": "https://api.github.com/users/cristianomg/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianomg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianomg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianomg/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianomg/orgs",
      "repos_url": "https://api.github.com/users/cristianomg/repos",
      "events_url": "https://api.github.com/users/cristianomg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianomg/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "philipcristiano",
      "id": 36135,
      "node_id": "MDQ6VXNlcjM2MTM1",
      "avatar_url": "https://avatars.githubusercontent.com/u/36135?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/philipcristiano",
      "html_url": "https://github.com/philipcristiano",
      "followers_url": "https://api.github.com/users/philipcristiano/followers",
      "following_url": "https://api.github.com/users/philipcristiano/following{/other_user}",
      "gists_url": "https://api.github.com/users/philipcristiano/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/philipcristiano/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/philipcristiano/subscriptions",
      "organizations_url": "https://api.github.com/users/philipcristiano/orgs",
      "repos_url": "https://api.github.com/users/philipcristiano/repos",
      "events_url": "https://api.github.com/users/philipcristiano/events{/privacy}",
      "received_events_url": "https://api.github.com/users/philipcristiano/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianomj",
      "id": 8647704,
      "node_id": "MDQ6VXNlcjg2NDc3MDQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8647704?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianomj",
      "html_url": "https://github.com/cristianomj",
      "followers_url": "https://api.github.com/users/cristianomj/followers",
      "following_url": "https://api.github.com/users/cristianomj/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianomj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianomj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianomj/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianomj/orgs",
      "repos_url": "https://api.github.com/users/cristianomj/repos",
      "events_url": "https://api.github.com/users/cristianomj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianomj/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "CristianoSouza",
      "id": 6935877,
      "node_id": "MDQ6VXNlcjY5MzU4Nzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6935877?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CristianoSouza",
      "html_url": "https://github.com/CristianoSouza",
      "followers_url": "https://api.github.com/users/CristianoSouza/followers",
      "following_url": "https://api.github.com/users/CristianoSouza/following{/other_user}",
      "gists_url": "https://api.github.com/users/CristianoSouza/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CristianoSouza/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CristianoSouza/subscriptions",
      "organizations_url": "https://api.github.com/users/CristianoSouza/orgs",
      "repos_url": "https://api.github.com/users/CristianoSouza/repos",
      "events_url": "https://api.github.com/users/CristianoSouza/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CristianoSouza/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cristianofromagio",
      "id": 16294559,
      "node_id": "MDQ6VXNlcjE2Mjk0NTU5",
      "avatar_url": "https://avatars.githubusercontent.com/u/16294559?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cristianofromagio",
      "html_url": "https://github.com/cristianofromagio",
      "followers_url": "https://api.github.com/users/cristianofromagio/followers",
      "following_url": "https://api.github.com/users/cristianofromagio/following{/other_user}",
      "gists_url": "https://api.github.com/users/cristianofromagio/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cristianofromagio/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cristianofromagio/subscriptions",
      "organizations_url": "https://api.github.com/users/cristianofromagio/orgs",
      "repos_url": "https://api.github.com/users/cristianofromagio/repos",
      "events_url": "https://api.github.com/users/cristianofromagio/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cristianofromagio/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
''';
